### PR TITLE
reloc: add --verbose option to build_reloc.sh

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, pip, tar and zip are very chatty, they flood the stdout. but when performing packaging, if everything goes fine, these output are but distracting.

so, in this change, we disable the verbose output by default, and add an option to enable it for debugging purpose.

### CODE REVIEW

**Comment by tchaikov** [comment]
@fruch hi Israel, could you please help review this change?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@syuu1228 @yaronkaikov, FYI

**Comment by fruch** [comment]
@tchaikov can you take this change to scylla-core ?

**Comment by tchaikov** [comment]
> @tchaikov can you take this change to scylla-core ?
> 
> i.e. a PR with updating the submodule

@fruch thank you for the review and approval, i will create a PR to bump up the submodule tomorrow.

**Comment by mykaul** [comment]
It's not entirely clear to me the value - I prefer verbosity when building, but that's perhaps personal preference - I just wonder what the default should be and what we should have in CI / GH action / etc. vs a developer working on it.

**Comment by tchaikov** [comment]
> It's not entirely clear to me the value - I prefer verbosity when building, but that's perhaps personal preference - I just wonder what the default should be and what we should have in CI / GH action / etc. vs a developer working on it.

when a command is run by script, most of the time, i think we don't expect a chatty command. please image a `ssh` client which is has 20 `-v` enabled. or a `tar` which prints every single entry in it. i think, the same applies almost all of the command we use on daily basis when they are used in a script. no news is good news.

i am working on porting the packaging to CMake, but i fail to find the useful information when cqlsh packages itself in an efficient way. it just hurts my productivity.

**Comment by tchaikov** [comment]
if you still have concerns, we can reenable verbose output of pip, once the pip commands fail. my pain point is mostly the output of `tar` and `zip`.

**Comment by tchaikov** [comment]
> > @tchaikov can you take this change to scylla-core ?
> > i.e. a PR with updating the submodule
> 
> @fruch thank you for the review and approval, i will create a PR to bump up the submodule tomorrow.

https://github.com/scylladb/scylladb/pull/15401

**Pull request merged**
