### PR TITLE
Updated Scylla Driver[Issue #55]

### LINKED ISSUE #55: Use newer Python Scylla driver (3.26.3)
Currently, requirements file has:
```
scylla-driver==3.26.0
```

Time to upgrade.

### PR DESCRIPTION
**Pull request by muddi900**
Fixes #55

### CODE REVIEW

**Comment by mykaul** [comment]
Thanks @muddi900 for the quick fix! Did you sign the CLA already? If not, please do so first.

**Comment by muddi900** [comment]
Where may I find the agreement?

**Comment by mykaul** [comment]
> Where may I find the agreement?

Even better news - this is not needed for this repo!
So we can just review it (@fruch please)

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@muddi900 thanks for you contribution

**Pull request merged**
