### PR TITLE
cqlsh should use cql v4 by default when connecting #44

### PR DESCRIPTION
**Pull request by mykaul**
Fixes: #44

Signed-off-by: Yaniv Kaul <yaniv.kaul@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
@avikivity I see @mykaul used "Fixes:" with a colon and although I don't know yet if it will really close the issue, I am guessing it will because #44 now has a "Maybe fixed by..." with this issue, so apparently it was parsed correctly. So You were right, it probably works. I don't know why a few months ago it didn't work and left an open issue.

**Review by nyh — CHANGES_REQUESTED** [review]
Please include the motivation for the change in the commit message. It's fine to copy-paste text from the issue (#44) but not enough to link to it, it should be visible in "git log" without following links.

The patch looks good to me, but do we have anyone else to review it, preferably someone with a solid opinion on why we have our own for on cqlsh and whether the motivation of this patch fits with that purpose?

**Comment by mykaul** [comment]
> Please include the motivation for the change in the commit message. It's fine to copy-paste text from the issue (#44) but not enough to link to it, it should be visible in "git log" without following links.
> 
> The patch looks good to me, but do we have anyone else to review it, preferably someone with a solid opinion on why we have our own for on cqlsh and whether the motivation of this patch fits with that purpose?

Amended the commit message.

**Review by nyh — APPROVED** [review]
Thanks.
@mykaul do we have anyone else who cares about cqlsh and can review this patch, or we'll just have to trust my judgement?

**Comment by mykaul** [comment]
> Thanks. @mykaul do we have anyone else who cares about cqlsh and can review this patch, or we'll just have to trust my judgement?

It can wait for @fruch to return from PTO.

**Comment by mykaul** [comment]
@fruch - ping

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
